name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt install libfreetype6-dev libmotif-dev libpng-dev
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure --enable-multithreaded --enable-cmyk --with-freetype2-includes="/usr/include/freetype2/"
    - name: make
      run: make -j2
    - name: make install
      run: sudo make install
